import React, { useState, useEffect } from 'react';
import { SignalStrategy } from '../../types/signals';
import { ExpressionBuilder } from './ExpressionBuilder';

interface StrategyManagerProps {
  onSelectStrategy?: (strategyId: string) => void;
}

export const StrategyManager: React.FC<StrategyManagerProps> = ({ onSelectStrategy }) => {
  const [strategies, setStrategies] = useState<SignalStrategy[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [editingStrategy, setEditingStrategy] = useState<SignalStrategy | null>(null);

  useEffect(() => {
    loadStrategies();
  }, []);

  const loadStrategies = async () => {
    setLoading(true);
    setError(null);

    try {
      const result = await window.electron.invoke('get_signal_strategies', {});
      if (result.success && result.strategies) {
        setStrategies(result.strategies);
      } else {
        setError(result.error || 'Failed to load strategies');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load strategies');
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (strategyId: string) => {
    if (!confirm('Are you sure you want to delete this strategy? This cannot be undone.')) return;

    try {
      const result = await window.electron.invoke('delete_signal_strategy', strategyId);
      if (result.success) {
        loadStrategies();
      } else {
        alert(`Failed to delete strategy: ${result.error}`);
      }
    } catch (err) {
      alert(`Error: ${err instanceof Error ? err.message : 'Unknown error'}`);
    }
  };

  const handleDuplicate = async (strategy: SignalStrategy) => {
    const newStrategy: SignalStrategy = {
      ...strategy,
      id: '', // Will be generated by backend
      name: `${strategy.name} (Copy)`,
      created_at: Date.now() / 1000,
      updated_at: Date.now() / 1000,
      version: 1
    };
    setEditingStrategy(newStrategy);
    setShowCreateModal(true);
  };

  const handleEdit = (strategy: SignalStrategy) => {
    setEditingStrategy(strategy);
    setShowCreateModal(true);
  };

  return (
    <div className="strategy-manager">
      <div className="manager-header">
        <h1>Strategy Manager</h1>
        <button
          onClick={() => {
            setEditingStrategy(null);
            setShowCreateModal(true);
          }}
          className="button-primary"
        >
          + Create Strategy
        </button>
      </div>

      {error && (
        <div className="error-banner">
          {error}
        </div>
      )}

      <div className="strategies-grid">
        {loading ? (
          <div className="loading">Loading strategies...</div>
        ) : strategies.length === 0 ? (
          <div className="no-strategies">
            <p>No strategies found. Create your first strategy to get started!</p>
            <button onClick={() => setShowCreateModal(true)} className="button-primary">
              Create Strategy
            </button>
          </div>
        ) : (
          strategies.map(strategy => (
            <StrategyCard
              key={strategy.id}
              strategy={strategy}
              onEdit={() => handleEdit(strategy)}
              onDuplicate={() => handleDuplicate(strategy)}
              onDelete={() => handleDelete(strategy.id)}
              onSelect={() => onSelectStrategy?.(strategy.id)}
            />
          ))
        )}
      </div>

      {showCreateModal && (
        <StrategyFormModal
          strategy={editingStrategy}
          onClose={() => {
            setShowCreateModal(false);
            setEditingStrategy(null);
          }}
          onSuccess={() => {
            setShowCreateModal(false);
            setEditingStrategy(null);
            loadStrategies();
          }}
        />
      )}

      <style>{`
        .strategy-manager {
          padding: 2rem;
          max-width: 1200px;
          margin: 0 auto;
        }

        .manager-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 2rem;
        }

        .manager-header h1 {
          margin: 0;
          font-size: 2rem;
        }

        .error-banner {
          background: #ffebee;
          border: 1px solid #ef5350;
          padding: 1rem;
          border-radius: 4px;
          margin-bottom: 1rem;
          color: #c62828;
        }

        .strategies-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
          gap: 1.5rem;
        }

        .loading,
        .no-strategies {
          text-align: center;
          padding: 3rem;
          color: #999;
        }

        .no-strategies p {
          margin-bottom: 1rem;
        }

        .button-primary {
          background: #2196f3;
          color: white;
          border: none;
          padding: 0.5rem 1rem;
          border-radius: 4px;
          cursor: pointer;
          font-size: 0.9rem;
          font-weight: 500;
        }

        .button-primary:hover {
          background: #1976d2;
        }
      `}</style>
    </div>
  );
};

interface StrategyCardProps {
  strategy: SignalStrategy;
  onEdit: () => void;
  onDuplicate: () => void;
  onDelete: () => void;
  onSelect: () => void;
}

const StrategyCard: React.FC<StrategyCardProps> = ({
  strategy,
  onEdit,
  onDuplicate,
  onDelete,
  onSelect
}) => {
  return (
    <div className="strategy-card" onClick={onSelect}>
      <div className="card-header">
        <h3>{strategy.name}</h3>
        <span className={`scope-badge ${strategy.scope}`}>
          {strategy.scope}
        </span>
      </div>

      {strategy.description && (
        <p className="card-description">{strategy.description}</p>
      )}

      <div className="card-details">
        <div className="detail-item">
          <label>Direction:</label>
          <span>{strategy.default_direction}</span>
        </div>
        <div className="detail-item">
          <label>Entry Conditions:</label>
          <span>{strategy.conditions.entry.length}</span>
        </div>
        <div className="detail-item">
          <label>Exit Conditions:</label>
          <span>{strategy.conditions.exit?.length || 0}</span>
        </div>
      </div>

      <div className="card-actions">
        <button
          onClick={(e) => {
            e.stopPropagation();
            onEdit();
          }}
          className="action-button edit"
          title="Edit"
        >
          ✏️ Edit
        </button>
        <button
          onClick={(e) => {
            e.stopPropagation();
            onDuplicate();
          }}
          className="action-button duplicate"
          title="Duplicate"
        >
          📋 Duplicate
        </button>
        <button
          onClick={(e) => {
            e.stopPropagation();
            onDelete();
          }}
          className="action-button delete"
          title="Delete"
        >
          🗑️ Delete
        </button>
      </div>

      <style>{`
        .strategy-card {
          background: white;
          border: 1px solid #e0e0e0;
          border-radius: 8px;
          padding: 1.5rem;
          cursor: pointer;
          transition: all 0.2s;
        }

        .strategy-card:hover {
          border-color: #2196f3;
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        }

        .card-header {
          display: flex;
          justify-content: space-between;
          align-items: start;
          margin-bottom: 1rem;
        }

        .card-header h3 {
          margin: 0;
          font-size: 1.2rem;
          color: #333;
        }

        .scope-badge {
          padding: 0.25rem 0.75rem;
          border-radius: 12px;
          font-size: 0.75rem;
          font-weight: 500;
          text-transform: capitalize;
        }

        .scope-badge.user {
          background: #e3f2fd;
          color: #1976d2;
        }

        .scope-badge.global {
          background: #f3e5f5;
          color: #7b1fa2;
        }

        .card-description {
          color: #666;
          font-size: 0.9rem;
          margin: 0 0 1rem 0;
          line-height: 1.5;
        }

        .card-details {
          display: flex;
          flex-direction: column;
          gap: 0.5rem;
          margin-bottom: 1rem;
          padding: 1rem;
          background: #f5f5f5;
          border-radius: 4px;
        }

        .detail-item {
          display: flex;
          justify-content: space-between;
          font-size: 0.85rem;
        }

        .detail-item label {
          color: #666;
          font-weight: 500;
        }

        .card-actions {
          display: flex;
          gap: 0.5rem;
          padding-top: 1rem;
          border-top: 1px solid #e0e0e0;
        }

        .action-button {
          flex: 1;
          background: white;
          border: 1px solid #ccc;
          padding: 0.5rem;
          border-radius: 4px;
          cursor: pointer;
          font-size: 0.85rem;
          transition: all 0.2s;
        }

        .action-button:hover {
          background: #f5f5f5;
        }

        .action-button.edit:hover {
          background: #e3f2fd;
          border-color: #2196f3;
        }

        .action-button.duplicate:hover {
          background: #f3e5f5;
          border-color: #9c27b0;
        }

        .action-button.delete:hover {
          background: #ffebee;
          border-color: #f44336;
        }
      `}</style>
    </div>
  );
};

interface StrategyFormModalProps {
  strategy: SignalStrategy | null;
  onClose: () => void;
  onSuccess: () => void;
}

const StrategyFormModal: React.FC<StrategyFormModalProps> = ({ strategy, onClose, onSuccess }) => {
  const isEditing = !!strategy?.id;

  const [name, setName] = useState(strategy?.name || '');
  const [description, setDescription] = useState(strategy?.description || '');
  const [direction, setDirection] = useState<'long' | 'short' | 'auto'>(
    strategy?.default_direction || 'auto'
  );
  const [scope, setScope] = useState<'user' | 'global'>(strategy?.scope || 'user');
  const [entryExpressions, setEntryExpressions] = useState<string[]>(
    strategy?.conditions.entry || ['']
  );
  const [exitExpressions, setExitExpressions] = useState<string[]>(
    strategy?.conditions.exit || []
  );
  const [exitLogic, setExitLogic] = useState<'any' | 'all'>(
    (strategy?.metadata.exit_logic as 'any' | 'all') || 'any'
  );
  const [reversalMode, setReversalMode] = useState<
    'no-auto-reversal' | 'auto-reversal-to-opposite' | 'auto-reversal-with-confirmation'
  >((strategy?.metadata.reversal_mode as any) || 'no-auto-reversal');

  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async () => {
    // Validation
    if (!name.trim()) {
      setError('Strategy name is required');
      return;
    }

    const validEntries = entryExpressions.filter(e => e.trim());
    if (validEntries.length === 0) {
      setError('At least one entry condition is required');
      return;
    }

    setSaving(true);
    setError(null);

    try {
      const strategyData = {
        name: name.trim(),
        description: description.trim(),
        conditions: {
          entry: validEntries,
          exit: exitExpressions.filter(e => e.trim())
        },
        default_direction: direction,
        scope,
        metadata: {
          exit_logic: exitLogic,
          reversal_mode: reversalMode
        }
      };

      const result = isEditing
        ? await window.electron.invoke('update_signal_strategy', strategy.id, strategyData)
        : await window.electron.invoke('create_signal_strategy', strategyData);

      if (result.success) {
        onSuccess();
      } else {
        setError(result.error || 'Failed to save strategy');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setSaving(false);
    }
  };

  return (
    <>
      <div className="strategy-form-modal" onClick={onClose}>
        <div className="modal-content" onClick={(e) => e.stopPropagation()}>
          <div className="modal-header">
            <h2>{isEditing ? 'Edit Strategy' : 'Create Strategy'}</h2>
            <button onClick={onClose} className="close-button">✕</button>
          </div>

          <div className="modal-body">
            {error && (
              <div className="error-message">{error}</div>
            )}

            <div className="form-section">
              <h3>Basic Information</h3>
              <div className="form-group">
                <label>Strategy Name *</label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="e.g., RSI Mean Reversion"
                  className="form-control"
                />
              </div>

              <div className="form-group">
                <label>Description</label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Describe your strategy..."
                  className="form-control"
                  rows={3}
                />
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Default Direction *</label>
                  <select
                    value={direction}
                    onChange={(e) => setDirection(e.target.value as any)}
                    className="form-control"
                  >
                    <option value="auto">Auto</option>
                    <option value="long">Long Only</option>
                    <option value="short">Short Only</option>
                  </select>
                </div>

                <div className="form-group">
                  <label>Scope *</label>
                  <select
                    value={scope}
                    onChange={(e) => setScope(e.target.value as any)}
                    className="form-control"
                  >
                    <option value="user">User (Private)</option>
                    <option value="global">Global (Shared)</option>
                  </select>
                </div>
              </div>
            </div>

            <div className="form-section">
              <h3>Entry Conditions *</h3>
              {entryExpressions.map((expr, index) => (
                <div key={index} className="expression-group">
                  <div className="expression-header">
                    <label>Entry Condition {index + 1}</label>
                    {entryExpressions.length > 1 && (
                      <button
                        onClick={() => setEntryExpressions(entryExpressions.filter((_, i) => i !== index))}
                        className="button-link"
                      >
                        Remove
                      </button>
                    )}
                  </div>
                  <ExpressionBuilder
                    value={expr}
                    onChange={(newExpr) => {
                      const updated = [...entryExpressions];
                      updated[index] = newExpr;
                      setEntryExpressions(updated);
                    }}
                    placeholder="Entry condition expression"
                  />
                </div>
              ))}
              <button
                onClick={() => setEntryExpressions([...entryExpressions, ''])}
                className="button-secondary small"
              >
                + Add Entry Condition
              </button>
            </div>

            <div className="form-section">
              <h3>Exit Conditions (Optional)</h3>
              {exitExpressions.length > 0 && (
                <div className="form-group">
                  <label>Exit Logic</label>
                  <select
                    value={exitLogic}
                    onChange={(e) => setExitLogic(e.target.value as any)}
                    className="form-control"
                  >
                    <option value="any">Any (Exit on first condition met)</option>
                    <option value="all">All (Exit only when all conditions met)</option>
                  </select>
                </div>
              )}

              {exitExpressions.map((expr, index) => (
                <div key={index} className="expression-group">
                  <div className="expression-header">
                    <label>Exit Condition {index + 1}</label>
                    <button
                      onClick={() => setExitExpressions(exitExpressions.filter((_, i) => i !== index))}
                      className="button-link"
                    >
                      Remove
                    </button>
                  </div>
                  <ExpressionBuilder
                    value={expr}
                    onChange={(newExpr) => {
                      const updated = [...exitExpressions];
                      updated[index] = newExpr;
                      setExitExpressions(updated);
                    }}
                    placeholder="Exit condition expression"
                  />
                </div>
              ))}
              <button
                onClick={() => setExitExpressions([...exitExpressions, ''])}
                className="button-secondary small"
              >
                + Add Exit Condition
              </button>
            </div>

            <div className="form-section">
              <h3>Reversal Behavior</h3>
              <div className="form-group">
                <label>Reversal Mode</label>
                <select
                  value={reversalMode}
                  onChange={(e) => setReversalMode(e.target.value as any)}
                  className="form-control"
                >
                  <option value="no-auto-reversal">No Auto Reversal</option>
                  <option value="auto-reversal-to-opposite">Auto Reversal to Opposite</option>
                  <option value="auto-reversal-with-confirmation">Auto Reversal with Confirmation</option>
                </select>
                <div className="help-text">
                  {reversalMode === 'no-auto-reversal' && 'Manual control only'}
                  {reversalMode === 'auto-reversal-to-opposite' && 'Automatically reverse position when conditions trigger'}
                  {reversalMode === 'auto-reversal-with-confirmation' && 'Reverse only when confirmed by entry conditions'}
                </div>
              </div>
            </div>
          </div>

          <div className="modal-footer">
            <button onClick={handleSubmit} disabled={saving} className="button-primary">
              {saving ? 'Saving...' : isEditing ? 'Update Strategy' : 'Create Strategy'}
            </button>
            <button onClick={onClose} className="button-secondary">
              Cancel
            </button>
          </div>
        </div>
      </div>

      <style>{`
        .strategy-form-modal {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(0, 0, 0, 0.5);
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 1000;
          padding: 1rem;
        }

        .strategy-form-modal .modal-content {
          background: white;
          border-radius: 8px;
          max-width: 800px;
          width: 100%;
          max-height: 90vh;
          display: flex;
          flex-direction: column;
          box-shadow: 0 10px 40px rgba(0, 0, 0, 0.3);
        }

        .strategy-form-modal .modal-header {
          padding: 1.5rem;
          border-bottom: 1px solid #e0e0e0;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }

        .strategy-form-modal .modal-header h2 {
          margin: 0;
          font-size: 1.5rem;
        }

        .strategy-form-modal .close-button {
          background: none;
          border: none;
          font-size: 1.5rem;
          cursor: pointer;
          color: #999;
          padding: 0;
          width: 2rem;
          height: 2rem;
        }

        .strategy-form-modal .close-button:hover {
          color: #333;
        }

        .strategy-form-modal .modal-body {
          padding: 1.5rem;
          overflow-y: auto;
          flex: 1;
        }

        .strategy-form-modal .modal-footer {
          padding: 1rem 1.5rem;
          border-top: 1px solid #e0e0e0;
          display: flex;
          gap: 1rem;
          justify-content: flex-end;
        }

        .error-message {
          background: #ffebee;
          border: 1px solid #ef5350;
          padding: 1rem;
          border-radius: 4px;
          margin-bottom: 1rem;
          color: #c62828;
        }

        .form-section {
          margin-bottom: 2rem;
        }

        .form-section h3 {
          margin: 0 0 1rem 0;
          font-size: 1.1rem;
          color: #333;
        }

        .form-group {
          margin-bottom: 1rem;
        }

        .form-group label {
          display: block;
          font-weight: 500;
          margin-bottom: 0.5rem;
          font-size: 0.9rem;
          color: #333;
        }

        .form-control {
          width: 100%;
          padding: 0.5rem;
          border: 1px solid #ccc;
          border-radius: 4px;
          font-size: 0.9rem;
          font-family: inherit;
        }

        .form-control:focus {
          outline: none;
          border-color: #2196f3;
        }

        textarea.form-control {
          resize: vertical;
        }

        .form-row {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 1rem;
        }

        .expression-group {
          margin-bottom: 1rem;
          padding: 1rem;
          border: 1px solid #e0e0e0;
          border-radius: 4px;
        }

        .expression-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 0.5rem;
        }

        .expression-header label {
          font-weight: 500;
          color: #666;
        }

        .help-text {
          margin-top: 0.5rem;
          font-size: 0.85rem;
          color: #666;
          font-style: italic;
        }

        .button-primary {
          background: #2196f3;
          color: white;
          border: none;
          padding: 0.5rem 1rem;
          border-radius: 4px;
          cursor: pointer;
          font-size: 0.9rem;
          font-weight: 500;
        }

        .button-primary:hover:not(:disabled) {
          background: #1976d2;
        }

        .button-primary:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .button-secondary {
          background: white;
          border: 1px solid #ccc;
          padding: 0.5rem 1rem;
          border-radius: 4px;
          cursor: pointer;
          font-size: 0.9rem;
        }

        .button-secondary:hover {
          background: #f5f5f5;
        }

        .button-secondary.small {
          padding: 0.25rem 0.75rem;
          font-size: 0.85rem;
        }

        .button-link {
          background: none;
          border: none;
          color: #2196f3;
          cursor: pointer;
          text-decoration: underline;
          font-size: 0.85rem;
          padding: 0;
        }

        .button-link:hover {
          color: #1976d2;
        }
      `}</style>
    </>
  );
};
